# Generated by Django 3.0.6 on 2020-05-10 03:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_counter',
            new_name='OrderCounter',
        ),
        migrations.RenameModel(
            old_name='ScilianPizza',
            new_name='SicilianPizza',
        ),
        migrations.RenameModel(
            old_name='User_order',
            new_name='UserOrder',
        ),
    ]
