# Generated by Django 3.0.6 on 2020-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200510_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordercounter',
            name='id',
        ),
        migrations.AlterField(
            model_name='order2',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordercounter',
            name='counter',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
