# Generated by Django 3.0.6 on 2020-05-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200521_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='topping_1',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='topping_2',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='topping_3',
        ),
    ]
