# Generated by Django 3.0.6 on 2020-05-18 11:25

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200518_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name=orders.models.UserOrder)),
                ('category', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='order2',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderCounter',
        ),
        migrations.DeleteModel(
            name='Order2',
        ),
    ]
