# Generated by Django 3.0.6 on 2020-05-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200521_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='topping_1',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='top1', to='orders.Topping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topping_2',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='top2', to='orders.Topping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topping_3',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='top3', to='orders.Topping'),
            preserve_default=False,
        ),
    ]
