# Generated by Django 3.0.6 on 2020-05-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200521_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.UserOrder'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='topping_1',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='topping_2',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='topping_3',
            field=models.CharField(default='none', max_length=32),
        ),
    ]
