# Generated by Django 3.0.6 on 2020-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200525_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
    ]
