# Generated by Django 3.0.6 on 2020-05-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200525_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(default='initiated', max_length=64),
        ),
    ]
