# Generated by Django 3.0.6 on 2020-05-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200525_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='totalPrice',
            new_name='totalPriceItem',
        ),
    ]
