# Generated by Django 3.0.6 on 2020-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200526_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='totalPriceItem',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='totalPriceOrder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
